######################################################################
# Automatically generated by qmake (2.01a) ?? 5? 8 00:20:09 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += dlinklist.h qt1.h dlinklist.c
FORMS += qt1.ui
SOURCES += dlinklist.c main.cpp qt1.cpp
